server:
 port: 8080

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
   username: root
   password: testtest


 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
   hibernate:
     ddl-auto: update
   show-sql: true

indexing-settings:
  sites:
    - url: http://radiomv.ru/
      name: Радио
    - url: https://dombulgakova.ru/
      name: Дом Булгакова